version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: developersalesstore-api
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
